Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.311
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.488
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.414
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.082
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.703
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.804
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.473
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.939
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.050
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.799
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.068
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.970
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.408
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.199
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.313
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.679
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.119
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.951
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.006
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.895
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.216
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.328
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.272
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.535
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 293.410
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 265.575
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.575
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.444
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

