Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.008
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.450
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.435
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.733
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.940
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.327
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.393
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.239
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.205
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.738
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.567
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.321
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.854
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.229
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.833
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.105
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 293.942
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.124
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.193
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 292.133
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.523
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 292.254
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.869
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.405
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.423
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 285.262
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.614
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.948
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.372
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.540
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.344
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.543
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 32, in get_html_from_site
    iframe = driver.find_element_by_xpath(xpath_iframe_lp)  # switch to it
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Translation isn't loaded
Message: unexpected alert open: {Alert text : Translation isn't loaded}
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.089
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.146
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.405
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.567
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.959
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.804
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.324
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.133
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.267
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.914
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.570
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.729
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

