Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.855
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.982
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.149
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.431
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 290.977
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.851
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 293.610
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.063
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.862
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 291.516
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 290.951
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.448
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 291.855
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.782
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.169
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.969
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.205
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.106
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.998
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.301
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.555
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.012
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 293.246
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.374
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.610
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.637
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.113
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 272.171
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 285.036
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.196
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.689
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.642
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.921
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.125
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.032
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.583
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.059
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.932
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.649
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.543
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.080
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.400
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.130
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.142
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.315
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.509
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.694
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.498
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.183
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.015
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.457
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.863
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.154
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.825
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.427
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.503
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.187
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.696
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.686
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 294.897
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 292.655
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.772
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.416
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.395
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.001
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.044
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.147
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.952
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.155
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.691
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.877
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.111
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.611
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 295.076
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.777
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.97)

